logger:
  console:
    tresholdFilter: ${logger.console.tresholdFilter}

  file:
    tresholdFilter: ${logger.file.tresholdFilter}

indexing-settings:
    sitesList:
        -
          url: https://www.lenta.ru
          name: ?????.??
        -
          url: https://www.skillbox.ru
          name: Skillbox
        -
          url: https://www.playback.ru
          name: Playback.Ru