logger:
  console:
    tresholdFilter: ${logger.console.tresholdFilter}

  file:
    tresholdFilter: ${logger.file.tresholdFilter}

indexing-settings:
    sites-list:
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: Playback.Ru