indexing-settings:
    sites:
        - url: https://www.lenta.ru
          name: ?????.??
        - url: https://www.skillbox.ru
          name: Skillbox
        - url: https://www.playback.ru
          name: Playback.Ru